version: '3'

services:
  nodejs:
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_USER_PASSWORD}
    networks:
      - app-network
    command: npm run dev 

  db:
    image: mysql
    container_name: db
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:     
      - dbdata:/data/db
    networks:
      - app-network  

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - app-network 

networks:
  app-network:
    driver: bridge

volumes:
  dbdata: 